### ISSUE TITLE
BLD: Proposed new tag release

### ISSUE THREAD

**Issue by cpelley** [SciTools/biggus#114]
I propose that a new biggus tag release be made, allowing those packages which depend on recent API changes of biggus to be reference by its tag release.

In particular, I'm pushing for this as a result of the following commit (https://github.com/SciTools/biggus/commit/89ced476848882cb84616b7d9c2ce2959d7ae294).

**Comment by rhattersley** [comment]
I've created [v0.8.0](https://github.com/SciTools/biggus/releases/tag/v0.8.0). Enjoy! :grin:

**Comment by QuLogic** [comment]
PyPI too?

**Comment by rhattersley** [comment]
> PS, did you know you can have Travis upload to PyPI automatically? (I just found this info.)

Thanks for the reminder, I'd forgotten that existed! :+1:

**Comment by rhattersley** [comment]
> PyPI too?

I'm having trouble with this ... it keeps hanging on the upload. :unamused:

**Comment by cpelley** [comment]
> PS, did you know you can have Travis upload to PyPI automatically? (I just found this info.)

WOW this is fantastic idea!

**Comment by cpelley** [comment]
> I've created v0.8.0. Enjoy! :grin:

Thanks for this @rhattersley
