### ISSUE TITLE
AssertionError when loading the vertical coordinate of an iris cube.

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/biggus#143]
I am not sure if this is a bug in Biggus or in iris.  If I try to load a cube vertical coordinate directly, like this:

```python
>>> import iris
>>> url = "http://colossus.dl.stevens-tech.edu:8080/thredds/dodsC/latest/Bight_gcmplt.nc"
>>> cube = iris.load_cube(url, 'sea_water_salinity')
>>> cube.coord('sea_surface_height_above_reference_ellipsoid')
<repr(<iris.coords.AuxCoord at 0x7f902daf6750>) failed: AssertionError: >
```

and accessing the points trigger the Exception.

```python
Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in __init__(self, array1, array2, numpy_op, ma_op)
   2679 
   2680         # TODO: Type-promotion
-> 2681         assert array1.dtype == array2.dtype
   2682         self._array1 = array1
   2683         self._array2 = array2
```

But if I load the `cube.coords()`, then everything works.  [Here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/f79b25180950b9d28972/raw/57d04028c5994e8c5c5869c55ed08dcf35300514/coords_bug.ipynb) is a notebook showing this issue.

**Comment by pelson** [comment]
Relevant comment: https://github.com/SciTools/biggus/issues/25#issuecomment-29367825

This just needs implementing. Hopefully wouldn't be too difficult to implement, though it looks like there is a decision to be made about honouring numpy's implementation etc.
