### ISSUE TITLE
biggus.Array.ndarray(...) and masked_array(...) don't always return arrays

### ISSUE THREAD

**Issue by djkirkham** [SciTools/biggus#175]
In certain degenerate cases, the result of calling `ndarray(...)` or `masked_array(...)` will be a NumPy numeric type, not an array. For example:

```
import biggus
import numpy as np

a = np.array(3)
b = biggus.NumpyArrayAdapter(a)
c = b * 4
d = c.ndarray()

print type(d)
```

The result is a NumPy integer type. This is consistent with the behaviour of NumPy arrays, but is confusing, especially since the docstrings for these functions explicitly state that they return a NumPy ndarray/MaskedArray instance.

**Comment by pelson** [comment]
Seems unlikely that we are going to change this behaviour in biggus, at this point (due to our general preference for dask.array).
I'm going to close this issue out.

Thanks
