### ISSUE TITLE
 version 0.14.0 is missing tar-ball on pypi 

### ISSUE THREAD

**Issue by arunpersaud** [SciTools/biggus#186]
the latest version seems to be missing a tar-ball on pypi. Would be great to have those available over there. Thanks

**Comment by marqh** [comment]
this is still a problem, and I don't see how to fix it; is anyone else able to shed some light?

**Comment by pelson** [comment]
**Finally** got this done - sorry I didn't see this *much, much* sooner.

----

For the record, uploading to pypi is pretty straightforward with twine:

```
git co v0.14.0 
python setup.py sdist
twine upload dist/Biggus-0.14.0.tar.gz
```
