### ISSUE TITLE
__array__ allows implicit realization of data

### ISSUE THREAD

**Issue by djkirkham** [SciTools/biggus#196]
I recently encountered a bug where a numpy function was implicitly realizing the data in a biggus array through (I presume) a call to `__array__` (https://github.com/SciTools/biggus/pull/195) . Given that the biggus docs state "Conversion to a concrete NumPy ndarray requires an explicit method call," is it wise to include this function?

**Comment by pelson** [comment]
This was the intended implication of #129. It is also the behaviour of tools like ``dask.array``. I completely agree that there is a risk of easily missing this subtlety, but I think the convenience of ``np.sin(biggus_array)`` trumped the cost. If we were making the same decision today, it might actually have been better to depend on a very modern numpy (>=1.13) and make use of its new subclassing powers.

Closing this one out, as I don't think we are going to fix it.
