### ISSUE TITLE
Is there a way to broadcast biggus arrays as numpy?

### ISSUE THREAD

**Issue by guziy** [SciTools/biggus#206]
Hi I am trying to calculate some deviations from a mean as:

```python
diff = biggus.subtract(seasonal_means, clim_mean.masked_array()[np.newaxis, :, :])
```

where `seasonal_means` is 3D and `clim_mean` is 2D. So in order for them to have the same shapes I convert clim_mean to the np.array and then use np.newaxis to broadcast, Is there a better way to do it ?
Because like this, the `clim_mean` is forced to be evaluated.

Cheers

**Comment by pp-mo** [comment]
Suggest: wrap the 'real' array with an array adapter, and use `biggus.BroadcastArray` ?

**Comment by pp-mo** [comment]
> Suggest:

But actually I think **you don't even need any of this**,
as biggus supports newaxis indexing, and will broadcast just like numpy anyway...
```
>>> a1 = np.array([[11, 12, 13], [21, 22, 23]])
>>> a1
array([[11, 12, 13],
       [21, 22, 23]])
>>> a2 = np.zeros((2,2,3)) + np.array([[[100]], [[200]]])
>>> a2
array([[[ 100.,  100.,  100.],
        [ 100.,  100.,  100.]],

       [[ 200.,  200.,  200.],
        [ 200.,  200.,  200.]]])
>>> ba1 = biggus.NumpyArrayAdapter(a1)
>>> bz = biggus.subtract(a2, ba1[np.newaxis, ...])
>>> bz
<_Elementwise shape=(2, 2, 3) dtype=dtype('float64')>
>>> bz.ndarray()
array([[[  89.,   88.,   87.],
        [  79.,   78.,   77.]],

       [[ 189.,  188.,  187.],
        [ 179.,  178.,  177.]]])
```

In fact, you don't even need the newaxis, as that an initial newaxis is handled by automatic broadcasting rules (a la numpy):
```
>>> bz2 = biggus.subtract(a2, ba1)
>>> bz2.ndarray()
array([[[  89.,   88.,   87.],
        [  79.,   78.,   77.]],

       [[ 189.,  188.,  187.],
        [ 179.,  178.,  177.]]])
>>> 
```

**Comment by guziy** [comment]
Thanks @pp-mo:

Cheers
