### ISSUE TITLE
Simple element-wise arithmetic

### ISSUE THREAD

**Issue by rhattersley** [SciTools/biggus#25]
Add support for deferred element-wise add, subtract, multiply, etc. of Arrays with identical shapes. (i.e. There is no need to support broadcasting at this stage.)

```
>>> assert model.shape == analysis.shape
>>> error = model - analysis
>>> isinstance(error, biggus.Array)
True
>>> error = error * error
>>> isinstance(error, biggus.Array)
True
```

 - [x] Add
 - [x] Subtract
 - [x] Multiply
 - [x] Divide
 - [x] Square (?)
 - [x] Square-root

**Comment by bjlittle** [comment]
@rhattersley Does #145 close this issue also?

**Comment by rhattersley** [comment]
I think it's close enough - especially given the wooly nature of the original issue.
