### ISSUE TITLE
Define interface for mixed bounded/unbounded evaluation

### ISSUE THREAD

**Issue by rhattersley** [SciTools/biggus#52]
What should the public user API be to enable users to mix and match bounded (ndarray and/or MaskedArray) with unbounded (e.g. netCDF variable) evaluation?

See https://github.com/SciTools/biggus/wiki/Processing

Also, consider:
- How to make this consistent with any special-case methods/functions which deal with simple cases? For example `my_array.ndarray()` or `biggus.save()` (which currently saves a single array to a single variable). NB. It is perfectly legitimate (and possibly even desirable) to change the existing methods/functions, just as much as it is to define new ones.
- What is the interface between biggus and a (possibly unbounded) save target? For example, if saving to a netCDF variable does the user need to ensure the variable has the correct shape before requesting the save? We don't want to have biggus doing any "magic".)

**Comment by pelson** [comment]
Closing this as WONTFIX - especially given the general recommendation of using ``dask.array`` over ``biggus``.
