### ISSUE TITLE
biggus should implement the ndarray interface

### ISSUE THREAD

**Issue by shoyer** [SciTools/biggus#66]
Implementation would be a one-liner. Just add the following method to `biggus.Array`:
```python
    def __array__(self, dtype=None):
        """NumPy array interface"""
        return self.ndarray()
```

Unfortunately, it's not as easy to support casting to masked arrays, although it looks like that is [possible](https://github.com/numpy/numpy/blob/v1.8.1/numpy/ma/core.py#L2648) by adding a `_mask` property.

The reason I have not submitted this as a pull request (yet) is that there is a trade-off here:
- Positives: This would make it dead easy to use biggus arrays in external packages (e.g., Iris or [xray](https://github.com/akleeman/xray)) without needing to do any un-Pythonic `isinstance` or `hasattr` type inspection to figure out how to make a concrete array. NumPy functions like `np.asarray` or `np.sin` would *just work*, making biggus arrays immediately compatible with tons of other code. By default, all arrays would be evaluated, but numpy also has hooks for ufuncs that would let you handle them in a lazy fashion. 
- Negatives: Writing `np.array([[small_array] * 1000] * 5)` will evaluate the array, unless you use the keyword argument `dtype=object`, which also would need to be sprinkled throughout biggus' code in a few places. Creating such arrays of arrays could be more awkward.

In my opinion, this is not much of a downside. Most users won't be making ArrayStacks from scratch, and people writing library code can use native Python data structures (which could be automatically cast to object ndarrays) or learn to write `dtype=object`. Thoughts?

**Comment by pelson** [comment]
``__array__`` has been implemented in #129.

**Comment by rhattersley** [comment]
> I would argue that np.asarray(big_array) is just as explicit as as big_array.ndarray(). The difference is that it uses a standard interface.

@shoyer - thank you for the original nudge ... I got there in the end. :wink:

**Comment by shoyer** [comment]
@rhattersley Actually, thank you! It looks like biggus has been getting some nice improvements lately...
