### ISSUE TITLE
Setting fill_value interfere with iris._merge

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/biggus#94]
Assigning a `fill_value` property in [Array.fill_value](https://github.com/SciTools/biggus/blob/48bbfde21769a2d840128e3e196d76f4598c94c7/biggus/__init__.py#L48) will create a masked array default `fill_value` even when the original data is not masked.  

That [prevents cubes merging](https://github.com/SciTools/iris/blob/78bf7e2492ac538674395f6f295fabb61899fa88/lib/iris/_merge.py#L1553) in iris.

The failure happens when slicing cubes and trying to merge them again.  If one of the slices happens to be masked and the other is not the merging will fail.  That occurs because the merging will be between the original `fill_value`, from the original cube metadata, and the default `fill_value` assigned by biggus `lazy_data()`.

Don't know if the best approach would be for iris to preserve the original `fill_value` when slicing data that is masked (even when there is nothing to fill -- that would be an iris fix), or if biggus could avoid attaching this property to non-masked objects.

**Comment by pelson** [comment]
@ocefpaf - it is hard to be certain, but I think #105 addressed this problem. Do you have a simple case with which we can reproduce the problem?

**Comment by ocefpaf** [comment]
Yes I do .  I will test this later today (I am away from my laptop now) and close the issue if it works.

**Comment by ocefpaf** [comment]
Yes, this is fixed!  Thanks a lot @pelson

PS: I do not have a simple case, but I just removed my [workaround](https://github.com/pyoceans/utilities/compare/master...ocefpaf:remove_standardize_fill_value?expand=1) for this issue and everything worked out fine in my notebooks.
