### ISSUE TITLE
Biggus 0.6 is available on github, but only 0.5 is available on pypi

### ISSUE THREAD

**Issue by jypeter** [SciTools/biggus#99]
I don't know if this is the right place to report this, but the IRIS requirements want biggus >= 0.6
- http://scitools.org.uk/iris/docs/latest/installing.html

and only 0.5 is available on pypi...
- https://pypi.python.org/pypi/Biggus/

**Comment by toddrjen** [comment]
The pypi release is out-of-date again (0.8.0 vs. 0.10.0).

**Comment by rhattersley** [comment]
Thanks for the nudge @toddrjen!
